/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { LowestPricedOffersInput } from './LowestPricedOffersInput.js'
import { Offer } from './Offer.js'

/**
 * The LowestPricedOffer model module.
 * @module pricing_v2022_05_01/model/LowestPricedOffer
 * @version 2022-05-01
 */
export class LowestPricedOffer {
  /**
   * Constructs a new <code>LowestPricedOffer</code>.
   * Describes the lowest priced offers for the specified item condition and offer type.
   * @alias module:pricing_v2022_05_01/model/LowestPricedOffer
   * @class
   * @param lowestPricedOffersInput {module:pricing_v2022_05_01/model/LowestPricedOffersInput}
   * @param offers {Array.<module:pricing_v2022_05_01/model/Offer>} A list of up to 20 lowest priced offers that match the criteria specified in `lowestPricedOffersInput`.
   */
  constructor (lowestPricedOffersInput, offers) {
    this.lowestPricedOffersInput = lowestPricedOffersInput
    this.offers = offers
  }

  /**
   * Constructs a <code>LowestPricedOffer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:pricing_v2022_05_01/model/LowestPricedOffer} obj Optional instance to populate.
   * @return {module:pricing_v2022_05_01/model/LowestPricedOffer} The populated <code>LowestPricedOffer</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new LowestPricedOffer()
      if (data.hasOwnProperty('lowestPricedOffersInput')) { obj.lowestPricedOffersInput = LowestPricedOffersInput.constructFromObject(data.lowestPricedOffersInput) }
      if (data.hasOwnProperty('offers')) { obj.offers = ApiClient.convertToType(data.offers, [Offer]) }
    }
    return obj
  }
}

/**
 * @member {module:pricing_v2022_05_01/model/LowestPricedOffersInput} lowestPricedOffersInput
 */
LowestPricedOffer.prototype.lowestPricedOffersInput = undefined

/**
 * A list of up to 20 lowest priced offers that match the criteria specified in `lowestPricedOffersInput`.
 * @member {Array.<module:pricing_v2022_05_01/model/Offer>} offers
 */
LowestPricedOffer.prototype.offers = undefined
