/**
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { AccountType } from './AccountType.js'
import { CarrierAccountInput } from './CarrierAccountInput.js'

/**
 * The LinkableAccountType model module.
 * @module shipping_v2/model/LinkableAccountType
 * @version v2
 */
export class LinkableAccountType {
  /**
   * Constructs a new <code>LinkableAccountType</code>.
   * Info About Linkable Account Type
   * @alias module:shipping_v2/model/LinkableAccountType
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>LinkableAccountType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:shipping_v2/model/LinkableAccountType} obj Optional instance to populate.
   * @return {module:shipping_v2/model/LinkableAccountType} The populated <code>LinkableAccountType</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new LinkableAccountType()
      if (data.hasOwnProperty('accountType')) { obj.accountType = AccountType.constructFromObject(data.accountType) }
      if (data.hasOwnProperty('carrierAccountInputs')) { obj.carrierAccountInputs = ApiClient.convertToType(data.carrierAccountInputs, [CarrierAccountInput]) }
    }
    return obj
  }
}

/**
 * @member {module:shipping_v2/model/AccountType} accountType
 */
LinkableAccountType.prototype.accountType = undefined

/**
 * A list of CarrierAccountInput
 * @member {Array.<module:shipping_v2/model/CarrierAccountInput>} carrierAccountInputs
 */
LinkableAccountType.prototype.carrierAccountInputs = undefined
