/**
 * Selling Partner API for Direct Fulfillment Shipping
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * The version of the OpenAPI document: 2021-12-28
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { Container } from './Container.js'
import { PartyIdentification } from './PartyIdentification.js'

/**
 * The CreateShippingLabelsRequest model module.
 * @module vendordfshipping_v2021_12_28/model/CreateShippingLabelsRequest
 * @version 2021-12-28
 */
export class CreateShippingLabelsRequest {
  /**
   * Constructs a new <code>CreateShippingLabelsRequest</code>.
   * The request body for the createShippingLabels operation.
   * @alias module:vendordfshipping_v2021_12_28/model/CreateShippingLabelsRequest
   * @class
   * @param sellingParty {module:vendordfshipping_v2021_12_28/model/PartyIdentification}
   * @param shipFromParty {module:vendordfshipping_v2021_12_28/model/PartyIdentification}
   */
  constructor (sellingParty, shipFromParty) {
    this.sellingParty = sellingParty
    this.shipFromParty = shipFromParty
  }

  /**
   * Constructs a <code>CreateShippingLabelsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendordfshipping_v2021_12_28/model/CreateShippingLabelsRequest} obj Optional instance to populate.
   * @return {module:vendordfshipping_v2021_12_28/model/CreateShippingLabelsRequest} The populated <code>CreateShippingLabelsRequest</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new CreateShippingLabelsRequest()
      if (data.hasOwnProperty('sellingParty')) { obj.sellingParty = PartyIdentification.constructFromObject(data.sellingParty) }
      if (data.hasOwnProperty('shipFromParty')) { obj.shipFromParty = PartyIdentification.constructFromObject(data.shipFromParty) }
      if (data.hasOwnProperty('containers')) { obj.containers = ApiClient.convertToType(data.containers, [Container]) }
    }
    return obj
  }
}

/**
 * @member {module:vendordfshipping_v2021_12_28/model/PartyIdentification} sellingParty
 */
CreateShippingLabelsRequest.prototype.sellingParty = undefined

/**
 * @member {module:vendordfshipping_v2021_12_28/model/PartyIdentification} shipFromParty
 */
CreateShippingLabelsRequest.prototype.shipFromParty = undefined

/**
 * A list of the packages in this shipment.
 * @member {Array.<module:vendordfshipping_v2021_12_28/model/Container>} containers
 */
CreateShippingLabelsRequest.prototype.containers = undefined
