/**
 * Selling Partner API for Merchant Fulfillment
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
* Enum class FileType.
* @enum {}
* @readonly
*/
export class FileType {
  /**
         * value: "application/pdf"
         * @const
         */
  'application/pdf' = 'application/pdf'

  /**
         * value: "application/zpl"
         * @const
         */
  'application/zpl' = 'application/zpl'

  /**
         * value: "image/png"
         * @const
         */
  'image/png' = 'image/png'

  /**
    * Returns a <code>FileType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:merchantfulfillment_v0/model/FileType} The enum <code>FileType</code> value.
    */
  static constructFromObject (object) {
    return object
  }
}
