/**
 * Selling Partner API for Uploads
 * The Uploads API lets you upload files that you can programmatically access using other Selling Partner APIs, such as the A+ Content API and the Messaging API.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js';
import sinon from 'sinon';
import { join } from 'path';

const modulePath = join(process.cwd(), 'src', 'uploads_v2020_11_01', 'index.js');
const SellingPartnerApiForUploads = await import(modulePath);

let instance;
let sandbox;
const testEndpoint = 'https://localhost:3000';
const testAccessToken = "testAccessToken";

// Helper function to generate random test data
function generateMockData(dataType, isArray = false) {
  if (!dataType) return {};

  // Handle array types
  if (isArray) {
    return [generateMockData(dataType), generateMockData(dataType)];
  }

  switch(dataType) {
    case 'String':
      return 'mock-' + Math.random().toString(36).substring(2, 10);
    case 'Number':
      return Math.floor(Math.random() * 1000);
    case 'Boolean':
      return Math.random() > 0.5;
    case 'Date':
      return new Date().toISOString();
    default:
      try {
        const ModelClass = SellingPartnerApiForUploads[dataType];
        if (ModelClass) {
          const instance = Object.create(ModelClass.prototype);
          return instance;
        }
      } catch (e) {
        console.error("Error creating instance of", dataType);
        return {};
      }
      return {};
  }
}

// Generate mock requests and responses for each operation
const mockcreateUploadDestinationForResourceData = {
  request: {
    'marketplaceIds': generateMockData('String', true),
    'contentMD5': generateMockData('String'),
    'resource': generateMockData('String'),
  },
  response: {
    data: generateMockData('CreateUploadDestinationResponse'),
    statusCode: 201,
    headers: {}
  }
};

describe('UploadsApi', () => {
  beforeEach(() => {
    sandbox = sinon.createSandbox();
    const apiClientInstance = new SellingPartnerApiForUploads.ApiClient(testEndpoint);
    apiClientInstance.applyXAmzAccessTokenToRequest(testAccessToken);
    sandbox.stub(apiClientInstance, 'callApi');
    instance = new SellingPartnerApiForUploads.UploadsApi(apiClientInstance);
  });

  afterEach(() => {
    sandbox.restore();
  });

  describe('createUploadDestinationForResource', () => {
    it('should successfully call createUploadDestinationForResource', async () => {
      instance.apiClient.callApi.resolves(mockcreateUploadDestinationForResourceData.response);

      const params = [
        mockcreateUploadDestinationForResourceData.request['marketplaceIds'],
        mockcreateUploadDestinationForResourceData.request['contentMD5'],
        mockcreateUploadDestinationForResourceData.request['resource'],
      ];
      const data = await instance.createUploadDestinationForResource(...params);

      expect(data instanceof SellingPartnerApiForUploads.CreateUploadDestinationResponse).to.be.true;
      expect(data).to.equal(mockcreateUploadDestinationForResourceData.response.data);
    });

    it('should successfully call createUploadDestinationForResourceWithHttpInfo', async () => {
      instance.apiClient.callApi.resolves(mockcreateUploadDestinationForResourceData.response);

      const params = [
        mockcreateUploadDestinationForResourceData.request['marketplaceIds'],
        mockcreateUploadDestinationForResourceData.request['contentMD5'],
        mockcreateUploadDestinationForResourceData.request['resource'],
      ];
      const response = await instance.createUploadDestinationForResourceWithHttpInfo(...params);

      expect(response).to.have.property('statusCode');
      expect(response.statusCode).to.equal(mockcreateUploadDestinationForResourceData.response.statusCode)
      expect(response).to.have.property('headers');
      expect(response).to.have.property('data');
      expect(response.data).to.equal(mockcreateUploadDestinationForResourceData.response.data)
    });

    it('should handle API errors', async () => {
      const errorResponse = {
        errors: new Error('Expected error to be thrown'),
        statusCode: 400,
        headers: {}
      };
      instance.apiClient.callApi.rejects(errorResponse);

      try {
        const params = [
          mockcreateUploadDestinationForResourceData.request['marketplaceIds'],
          mockcreateUploadDestinationForResourceData.request['contentMD5'],
          mockcreateUploadDestinationForResourceData.request['resource'],
        ];
        await instance.createUploadDestinationForResource(...params);
        throw new Error('Expected error to be thrown');
      } catch (error) {
        expect(error).to.exist;
        expect(error.statusCode).to.equal(400);
      }
    });
  });

  describe('constructor', () => {
    it('should use default ApiClient when none provided', () => {
      const defaultInstance = new SellingPartnerApiForUploads.UploadsApi();
      expect(defaultInstance.apiClient).to.equal(SellingPartnerApiForUploads.ApiClient.instance);
    });

    it('should use provided ApiClient', () => {
      const customClient = new SellingPartnerApiForUploads.ApiClient();
      const customInstance = new SellingPartnerApiForUploads.UploadsApi(customClient);
      expect(customInstance.apiClient).to.equal(customClient);
    });
  });
});
