/**
 * Selling Partner API for Catalog Items
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
 * The ClassificationRefinement model module.
 * @module catalogitems_v2022_04_01/model/ClassificationRefinement
 * @version 2022-04-01
 */
export class ClassificationRefinement {
  /**
   * Constructs a new <code>ClassificationRefinement</code>.
   * A classification that you can use to refine your search.
   * @alias module:catalogitems_v2022_04_01/model/ClassificationRefinement
   * @class
   * @param numberOfResults {Number} The estimated number of results that would be returned if you refine your search by the specified `classificationId`.
   * @param displayName {String} Display name for the classification.
   * @param classificationId {String} The identifier of the classification that you can use to refine your search.
   */
  constructor (numberOfResults, displayName, classificationId) {
    this.numberOfResults = numberOfResults
    this.displayName = displayName
    this.classificationId = classificationId
  }

  /**
   * Constructs a <code>ClassificationRefinement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:catalogitems_v2022_04_01/model/ClassificationRefinement} obj Optional instance to populate.
   * @return {module:catalogitems_v2022_04_01/model/ClassificationRefinement} The populated <code>ClassificationRefinement</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new ClassificationRefinement()
      if (data.hasOwnProperty('numberOfResults')) { obj.numberOfResults = ApiClient.convertToType(data.numberOfResults, 'Number') }
      if (data.hasOwnProperty('displayName')) { obj.displayName = ApiClient.convertToType(data.displayName, 'String') }
      if (data.hasOwnProperty('classificationId')) { obj.classificationId = ApiClient.convertToType(data.classificationId, 'String') }
    }
    return obj
  }
}

/**
 * The estimated number of results that would be returned if you refine your search by the specified `classificationId`.
 * @member {Number} numberOfResults
 */
ClassificationRefinement.prototype.numberOfResults = undefined

/**
 * Display name for the classification.
 * @member {String} displayName
 */
ClassificationRefinement.prototype.displayName = undefined

/**
 * The identifier of the classification that you can use to refine your search.
 * @member {String} classificationId
 */
ClassificationRefinement.prototype.classificationId = undefined
