/**
 * Selling Partner API for Catalog Items
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { ItemContributorRole } from './ItemContributorRole.js'

/**
 * The ItemContributor model module.
 * @module catalogitems_v2022_04_01/model/ItemContributor
 * @version 2022-04-01
 */
export class ItemContributor {
  /**
   * Constructs a new <code>ItemContributor</code>.
   * Individual contributor to the creation of an item, such as an author or actor.
   * @alias module:catalogitems_v2022_04_01/model/ItemContributor
   * @class
   * @param role {module:catalogitems_v2022_04_01/model/ItemContributorRole}
   * @param value {String} Name of the contributor, such as `Jane Austen`.
   */
  constructor (role, value) {
    this.role = role
    this.value = value
  }

  /**
   * Constructs a <code>ItemContributor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:catalogitems_v2022_04_01/model/ItemContributor} obj Optional instance to populate.
   * @return {module:catalogitems_v2022_04_01/model/ItemContributor} The populated <code>ItemContributor</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new ItemContributor()
      if (data.hasOwnProperty('role')) { obj.role = ItemContributorRole.constructFromObject(data.role) }
      if (data.hasOwnProperty('value')) { obj.value = ApiClient.convertToType(data.value, 'String') }
    }
    return obj
  }
}

/**
 * @member {module:catalogitems_v2022_04_01/model/ItemContributorRole} role
 */
ItemContributor.prototype.role = undefined

/**
 * Name of the contributor, such as `Jane Austen`.
 * @member {String} value
 */
ItemContributor.prototype.value = undefined
