/**
 * The Selling Partner API for Automotive.
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * The version of the OpenAPI document: 2024-11-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { VehicleStandard } from './VehicleStandard.js'

/**
 * The VehicleIdentifiers model module.
 * @module vehicles_v2024_11_01/model/VehicleIdentifiers
 * @version 2024-11-01
 */
export class VehicleIdentifiers {
  /**
   * Constructs a new <code>VehicleIdentifiers</code>.
   * Combination of vehicle standard and id that can uniquely identify a vehicle from Amazon&#39;s catalog.
   * @alias module:vehicles_v2024_11_01/model/VehicleIdentifiers
   * @class
   * @param standard {module:vehicles_v2024_11_01/model/VehicleStandard}
   * @param value {String} Id that can uniquely identify a vehicle based the vehicle identification standard.
   */
  constructor (standard, value) {
    this.standard = standard
    this.value = value
  }

  /**
   * Constructs a <code>VehicleIdentifiers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vehicles_v2024_11_01/model/VehicleIdentifiers} obj Optional instance to populate.
   * @return {module:vehicles_v2024_11_01/model/VehicleIdentifiers} The populated <code>VehicleIdentifiers</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new VehicleIdentifiers()
      if (data.hasOwnProperty('standard')) { obj.standard = VehicleStandard.constructFromObject(data.standard) }
      if (data.hasOwnProperty('value')) { obj.value = ApiClient.convertToType(data.value, 'String') }
    }
    return obj
  }
}

/**
 * @member {module:vehicles_v2024_11_01/model/VehicleStandard} standard
 */
VehicleIdentifiers.prototype.standard = undefined

/**
 * Id that can uniquely identify a vehicle based the vehicle identification standard.
 * @member {String} value
 */
VehicleIdentifiers.prototype.value = undefined
