/**
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * The version of the OpenAPI document: 2024-05-09
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
* Enum class InventoryUnitOfMeasurement.
* @enum {}
* @readonly
*/
export class InventoryUnitOfMeasurement {
  /**
         * value: "PRODUCT_UNITS"
         * @const
         */
  'PRODUCT_UNITS' = 'PRODUCT_UNITS'

  /**
         * value: "CASES"
         * @const
         */
  'CASES' = 'CASES'

  /**
         * value: "PALLETS"
         * @const
         */
  'PALLETS' = 'PALLETS'

  /**
    * Returns a <code>InventoryUnitOfMeasurement</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:awd_v2024_05_09/model/InventoryUnitOfMeasurement} The enum <code>InventoryUnitOfMeasurement</code> value.
    */
  static constructFromObject (object) {
    return object
  }
}
