/**
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
* Enum class ItemLabelPageType.
* @enum {}
* @readonly
*/
export class ItemLabelPageType {
  /**
         * value: "A4_21"
         * @const
         */
  'A4_21' = 'A4_21'

  /**
         * value: "A4_24"
         * @const
         */
  'A4_24' = 'A4_24'

  /**
         * value: "A4_24_64x33"
         * @const
         */
  'A4_24_64x33' = 'A4_24_64x33'

  /**
         * value: "A4_24_66x35"
         * @const
         */
  'A4_24_66x35' = 'A4_24_66x35'

  /**
         * value: "A4_24_70x36"
         * @const
         */
  'A4_24_70x36' = 'A4_24_70x36'

  /**
         * value: "A4_24_70x37"
         * @const
         */
  'A4_24_70x37' = 'A4_24_70x37'

  /**
         * value: "A4_24i"
         * @const
         */
  'A4_24i' = 'A4_24i'

  /**
         * value: "A4_27"
         * @const
         */
  'A4_27' = 'A4_27'

  /**
         * value: "A4_40_52x29"
         * @const
         */
  'A4_40_52x29' = 'A4_40_52x29'

  /**
         * value: "A4_44_48x25"
         * @const
         */
  'A4_44_48x25' = 'A4_44_48x25'

  /**
         * value: "Letter_30"
         * @const
         */
  'Letter_30' = 'Letter_30'

  /**
    * Returns a <code>ItemLabelPageType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:fulfillmentinbound_v2024_03_20/model/ItemLabelPageType} The enum <code>ItemLabelPageType</code> value.
    */
  static constructFromObject (object) {
    return object
  }
}
