/**
 * Selling Partner API for Direct Fulfillment Inventory Updates
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from './ApiClient.js'
import { Error } from './model/Error.js'
import { InventoryUpdate } from './model/InventoryUpdate.js'
import { ItemDetails } from './model/ItemDetails.js'
import { ItemQuantity } from './model/ItemQuantity.js'
import { PartyIdentification } from './model/PartyIdentification.js'
import { SubmitInventoryUpdateRequest } from './model/SubmitInventoryUpdateRequest.js'
import { SubmitInventoryUpdateResponse } from './model/SubmitInventoryUpdateResponse.js'
import { TransactionReference } from './model/TransactionReference.js'
import { UpdateInventoryApi } from './api/UpdateInventoryApi.js'

/**
* The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor&#39;s inventory updates..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* @module vendordfinventory_v1/index
* @version v1
*/
export {
  /**
     * The ApiClient constructor.
     * @property {module:vendordfinventory_v1/ApiClient}
     */
  ApiClient,

  /**
     * The Error model constructor.
     * @property {module:vendordfinventory_v1/model/Error}
     */
  Error,

  /**
     * The InventoryUpdate model constructor.
     * @property {module:vendordfinventory_v1/model/InventoryUpdate}
     */
  InventoryUpdate,

  /**
     * The ItemDetails model constructor.
     * @property {module:vendordfinventory_v1/model/ItemDetails}
     */
  ItemDetails,

  /**
     * The ItemQuantity model constructor.
     * @property {module:vendordfinventory_v1/model/ItemQuantity}
     */
  ItemQuantity,

  /**
     * The PartyIdentification model constructor.
     * @property {module:vendordfinventory_v1/model/PartyIdentification}
     */
  PartyIdentification,

  /**
     * The SubmitInventoryUpdateRequest model constructor.
     * @property {module:vendordfinventory_v1/model/SubmitInventoryUpdateRequest}
     */
  SubmitInventoryUpdateRequest,

  /**
     * The SubmitInventoryUpdateResponse model constructor.
     * @property {module:vendordfinventory_v1/model/SubmitInventoryUpdateResponse}
     */
  SubmitInventoryUpdateResponse,

  /**
     * The TransactionReference model constructor.
     * @property {module:vendordfinventory_v1/model/TransactionReference}
     */
  TransactionReference,

  /**
    * The UpdateInventoryApi service constructor.
    * @property {module:vendordfinventory_v1/api/UpdateInventoryApi}
    */
  UpdateInventoryApi
}
