/**
 * Selling Partner API for Easy Ship
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * The version of the OpenAPI document: 2022-03-23
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { LabelFormat } from './LabelFormat.js'
import { OrderScheduleDetails } from './OrderScheduleDetails.js'

/**
 * The CreateScheduledPackagesRequest model module.
 * @module easyship_v2022_03_23/model/CreateScheduledPackagesRequest
 * @version 2022-03-23
 */
export class CreateScheduledPackagesRequest {
  /**
   * Constructs a new <code>CreateScheduledPackagesRequest</code>.
   * The request body for the POST /easyShip/2022-03-23/packages/bulk API.
   * @alias module:easyship_v2022_03_23/model/CreateScheduledPackagesRequest
   * @class
   * @param marketplaceId {String} A string of up to 255 characters.
   * @param orderScheduleDetailsList {Array.<module:easyship_v2022_03_23/model/OrderScheduleDetails>} An array allowing users to specify orders to be scheduled.
   * @param labelFormat {module:easyship_v2022_03_23/model/LabelFormat}
   */
  constructor (marketplaceId, orderScheduleDetailsList, labelFormat) {
    this.marketplaceId = marketplaceId
    this.orderScheduleDetailsList = orderScheduleDetailsList
    this.labelFormat = labelFormat
  }

  /**
   * Constructs a <code>CreateScheduledPackagesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:easyship_v2022_03_23/model/CreateScheduledPackagesRequest} obj Optional instance to populate.
   * @return {module:easyship_v2022_03_23/model/CreateScheduledPackagesRequest} The populated <code>CreateScheduledPackagesRequest</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new CreateScheduledPackagesRequest()
      if (data.hasOwnProperty('marketplaceId')) { obj.marketplaceId = ApiClient.convertToType(data.marketplaceId, 'String') }
      if (data.hasOwnProperty('orderScheduleDetailsList')) { obj.orderScheduleDetailsList = ApiClient.convertToType(data.orderScheduleDetailsList, [OrderScheduleDetails]) }
      if (data.hasOwnProperty('labelFormat')) { obj.labelFormat = LabelFormat.constructFromObject(data.labelFormat) }
    }
    return obj
  }
}

/**
 * A string of up to 255 characters.
 * @member {String} marketplaceId
 */
CreateScheduledPackagesRequest.prototype.marketplaceId = undefined

/**
 * An array allowing users to specify orders to be scheduled.
 * @member {Array.<module:easyship_v2022_03_23/model/OrderScheduleDetails>} orderScheduleDetailsList
 */
CreateScheduledPackagesRequest.prototype.orderScheduleDetailsList = undefined

/**
 * @member {module:easyship_v2022_03_23/model/LabelFormat} labelFormat
 */
CreateScheduledPackagesRequest.prototype.labelFormat = undefined
