/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { Error } from './Error.js'
import { ListFinancialEventGroupsPayload } from './ListFinancialEventGroupsPayload.js'

/**
 * The ListFinancialEventGroupsResponse model module.
 * @module finances_v0/model/ListFinancialEventGroupsResponse
 * @version v0
 */
export class ListFinancialEventGroupsResponse {
  /**
   * Constructs a new <code>ListFinancialEventGroupsResponse</code>.
   * The response schema for the listFinancialEventGroups operation.
   * @alias module:finances_v0/model/ListFinancialEventGroupsResponse
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>ListFinancialEventGroupsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:finances_v0/model/ListFinancialEventGroupsResponse} obj Optional instance to populate.
   * @return {module:finances_v0/model/ListFinancialEventGroupsResponse} The populated <code>ListFinancialEventGroupsResponse</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new ListFinancialEventGroupsResponse()
      if (data.hasOwnProperty('payload')) { obj.payload = ListFinancialEventGroupsPayload.constructFromObject(data.payload) }
      if (data.hasOwnProperty('errors')) { obj.errors = ApiClient.convertToType(data.errors, [Error]) }
    }
    return obj
  }
}

/**
 * @member {module:finances_v0/model/ListFinancialEventGroupsPayload} payload
 */
ListFinancialEventGroupsResponse.prototype.payload = undefined

/**
 * A list of error responses returned when a request is unsuccessful.
 * @member {Array.<module:finances_v0/model/Error>} errors
 */
ListFinancialEventGroupsResponse.prototype.errors = undefined
