/**
 * Selling Partner API for Direct Fulfillment Payments
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js';
import { join } from 'path';

const modulePath = join(process.cwd(), 'src', 'vendordfpayments_v1', 'index.js');
const SellingPartnerApiForDirectFulfillmentPayments = await import(modulePath);

let instance;

beforeEach(() => {
  try {
    instance = new SellingPartnerApiForDirectFulfillmentPayments.AdditionalDetails();
  } catch (e) {
    //Handle the cases when this model extends another model by using Model.call(this);
    instance = Object.create(SellingPartnerApiForDirectFulfillmentPayments.AdditionalDetails.prototype);
  }
});

afterEach(() => {
  instance = null;
});

describe('AdditionalDetails', () => {
  it('should create an instance of AdditionalDetails', () => {
    expect(instance).to.be.a(SellingPartnerApiForDirectFulfillmentPayments.AdditionalDetails);
  });

  it('should have the property type', () => {
    // verify property exists
    expect(instance).to.have.property('type');

    // set and verify value
    const expectedValue = ['SUR', 'OCR', ][0];
    instance.type = expectedValue;
    expect(instance.type).to.equal(expectedValue);
  });

  it('should have the property detail', () => {
    // verify property exists
    expect(instance).to.have.property('detail');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.detail = expectedValue;
    expect(instance.detail).to.equal(expectedValue);
  });

  it('should have the property languageCode', () => {
    // verify property exists
    expect(instance).to.have.property('languageCode');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.languageCode = expectedValue;
    expect(instance.languageCode).to.equal(expectedValue);
  });

});

// Helper function to generate random test data
function generateMockData(dataType, isArray = false) {
  if (!dataType) return {};

  // Handle array types
  if (isArray) {
    return [generateMockData(dataType), generateMockData(dataType)];
  }

  switch(dataType) {
    case 'String':
      return 'mock-' + Math.random().toString(36).substring(2, 10);
    case 'Number':
      return Math.floor(Math.random() * 1000);
    case 'Boolean':
      return Math.random() > 0.5;
    case 'Date':
      return new Date().toISOString();
    default:
      try {
        const ModelClass = SellingPartnerApiForDirectFulfillmentPayments[dataType];
        if (ModelClass) {
          const instance = Object.create(ModelClass.prototype);
          return instance;
        }
      } catch (e) {
        console.error("Error creating instance of", dataType);
        return {};
      }
      return {};
  }
}
