/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { Error } from './Error.js'
import { GetPrepInstructionsResult } from './GetPrepInstructionsResult.js'

/**
 * The GetPrepInstructionsResponse model module.
 * @module fulfillmentinbound_v0/model/GetPrepInstructionsResponse
 * @version v0
 */
export class GetPrepInstructionsResponse {
  /**
   * Constructs a new <code>GetPrepInstructionsResponse</code>.
   * The response schema for the getPrepInstructions operation.
   * @alias module:fulfillmentinbound_v0/model/GetPrepInstructionsResponse
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>GetPrepInstructionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentinbound_v0/model/GetPrepInstructionsResponse} obj Optional instance to populate.
   * @return {module:fulfillmentinbound_v0/model/GetPrepInstructionsResponse} The populated <code>GetPrepInstructionsResponse</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new GetPrepInstructionsResponse()
      if (data.hasOwnProperty('payload')) { obj.payload = GetPrepInstructionsResult.constructFromObject(data.payload) }
      if (data.hasOwnProperty('errors')) { obj.errors = ApiClient.convertToType(data.errors, [Error]) }
    }
    return obj
  }
}

/**
 * @member {module:fulfillmentinbound_v0/model/GetPrepInstructionsResult} payload
 */
GetPrepInstructionsResponse.prototype.payload = undefined

/**
 * A list of error responses returned when a request is unsuccessful.
 * @member {Array.<module:fulfillmentinbound_v0/model/Error>} errors
 */
GetPrepInstructionsResponse.prototype.errors = undefined
