/**
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { CurbsidePickupConfiguration } from './CurbsidePickupConfiguration.js'
import { Duration } from './Duration.js'
import { InStorePickupConfiguration } from './InStorePickupConfiguration.js'
import { OperationalConfiguration } from './OperationalConfiguration.js'

/**
 * The PickupChannel model module.
 * @module supplysources_v2020_07_01/model/PickupChannel
 * @version 2020-07-01
 */
export class PickupChannel {
  /**
   * Constructs a new <code>PickupChannel</code>.
   * The pick up channel of a supply source.
   * @alias module:supplysources_v2020_07_01/model/PickupChannel
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>PickupChannel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:supplysources_v2020_07_01/model/PickupChannel} obj Optional instance to populate.
   * @return {module:supplysources_v2020_07_01/model/PickupChannel} The populated <code>PickupChannel</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new PickupChannel()
      if (data.hasOwnProperty('inventoryHoldPeriod')) { obj.inventoryHoldPeriod = Duration.constructFromObject(data.inventoryHoldPeriod) }
      if (data.hasOwnProperty('isSupported')) { obj.isSupported = ApiClient.convertToType(data.isSupported, 'Boolean') }
      if (data.hasOwnProperty('operationalConfiguration')) { obj.operationalConfiguration = OperationalConfiguration.constructFromObject(data.operationalConfiguration) }
      if (data.hasOwnProperty('inStorePickupConfiguration')) { obj.inStorePickupConfiguration = InStorePickupConfiguration.constructFromObject(data.inStorePickupConfiguration) }
      if (data.hasOwnProperty('curbsidePickupConfiguration')) { obj.curbsidePickupConfiguration = CurbsidePickupConfiguration.constructFromObject(data.curbsidePickupConfiguration) }
    }
    return obj
  }
}

/**
 * @member {module:supplysources_v2020_07_01/model/Duration} inventoryHoldPeriod
 */
PickupChannel.prototype.inventoryHoldPeriod = undefined

/**
 * @member {Boolean} isSupported
 */
PickupChannel.prototype.isSupported = undefined

/**
 * @member {module:supplysources_v2020_07_01/model/OperationalConfiguration} operationalConfiguration
 */
PickupChannel.prototype.operationalConfiguration = undefined

/**
 * @member {module:supplysources_v2020_07_01/model/InStorePickupConfiguration} inStorePickupConfiguration
 */
PickupChannel.prototype.inStorePickupConfiguration = undefined

/**
 * @member {module:supplysources_v2020_07_01/model/CurbsidePickupConfiguration} curbsidePickupConfiguration
 */
PickupChannel.prototype.curbsidePickupConfiguration = undefined
