/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { DeliveryDocument } from './DeliveryDocument.js'
import { DropOffLocation } from './DropOffLocation.js'

/**
 * The DeliveryInformation model module.
 * @module fulfillmentoutbound_v2020_07_01/model/DeliveryInformation
 * @version 2020-07-01
 */
export class DeliveryInformation {
  /**
   * Constructs a new <code>DeliveryInformation</code>.
   * The delivery information for the package. This information is available after the package is delivered.
   * @alias module:fulfillmentoutbound_v2020_07_01/model/DeliveryInformation
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>DeliveryInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentoutbound_v2020_07_01/model/DeliveryInformation} obj Optional instance to populate.
   * @return {module:fulfillmentoutbound_v2020_07_01/model/DeliveryInformation} The populated <code>DeliveryInformation</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new DeliveryInformation()
      if (data.hasOwnProperty('deliveryDocumentList')) { obj.deliveryDocumentList = ApiClient.convertToType(data.deliveryDocumentList, [DeliveryDocument]) }
      if (data.hasOwnProperty('dropOffLocation')) { obj.dropOffLocation = DropOffLocation.constructFromObject(data.dropOffLocation) }
    }
    return obj
  }
}

/**
 * A list of delivery documents for a package.
 * @member {Array.<module:fulfillmentoutbound_v2020_07_01/model/DeliveryDocument>} deliveryDocumentList
 */
DeliveryInformation.prototype.deliveryDocumentList = undefined

/**
 * @member {module:fulfillmentoutbound_v2020_07_01/model/DropOffLocation} dropOffLocation
 */
DeliveryInformation.prototype.dropOffLocation = undefined
