/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
 * The PaymentInformation model module.
 * @module fulfillmentoutbound_v2020_07_01/model/PaymentInformation
 * @version 2020-07-01
 */
export class PaymentInformation {
  /**
   * Constructs a new <code>PaymentInformation</code>.
   * The attributes related to the payment made from customer to seller for this order.
   * @alias module:fulfillmentoutbound_v2020_07_01/model/PaymentInformation
   * @class
   * @param paymentTransactionId {String} The transaction identifier of this payment.
   * @param paymentMode {String} The transaction mode of this payment.
   * @param paymentDate {Date} Date timestamp
   */
  constructor (paymentTransactionId, paymentMode, paymentDate) {
    this.paymentTransactionId = paymentTransactionId
    this.paymentMode = paymentMode
    this.paymentDate = paymentDate
  }

  /**
   * Constructs a <code>PaymentInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentoutbound_v2020_07_01/model/PaymentInformation} obj Optional instance to populate.
   * @return {module:fulfillmentoutbound_v2020_07_01/model/PaymentInformation} The populated <code>PaymentInformation</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new PaymentInformation()
      if (data.hasOwnProperty('paymentTransactionId')) { obj.paymentTransactionId = ApiClient.convertToType(data.paymentTransactionId, 'String') }
      if (data.hasOwnProperty('paymentMode')) { obj.paymentMode = ApiClient.convertToType(data.paymentMode, 'String') }
      if (data.hasOwnProperty('paymentDate')) { obj.paymentDate = ApiClient.convertToType(data.paymentDate, 'Date') }
    }
    return obj
  }
}

/**
 * The transaction identifier of this payment.
 * @member {String} paymentTransactionId
 */
PaymentInformation.prototype.paymentTransactionId = undefined

/**
 * The transaction mode of this payment.
 * @member {String} paymentMode
 */
PaymentInformation.prototype.paymentMode = undefined

/**
 * Date timestamp
 * @member {Date} paymentDate
 */
PaymentInformation.prototype.paymentDate = undefined
