/**
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js';
import { join } from 'path';

const modulePath = join(process.cwd(), 'src', 'supplysources_v2020_07_01', 'index.js');
const SellingPartnerApiForSupplySources = await import(modulePath);

let instance;

beforeEach(() => {
  try {
    instance = new SellingPartnerApiForSupplySources.SupplySource();
  } catch (e) {
    //Handle the cases when this model extends another model by using Model.call(this);
    instance = Object.create(SellingPartnerApiForSupplySources.SupplySource.prototype);
  }
});

afterEach(() => {
  instance = null;
});

describe('SupplySource', () => {
  it('should create an instance of SupplySource', () => {
    expect(instance).to.be.a(SellingPartnerApiForSupplySources.SupplySource);
  });

  it('should have the property supplySourceId', () => {
    // verify property exists
    expect(instance).to.have.property('supplySourceId');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.supplySourceId = expectedValue;
    expect(instance.supplySourceId).to.equal(expectedValue);
  });

  it('should have the property supplySourceCode', () => {
    // verify property exists
    expect(instance).to.have.property('supplySourceCode');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.supplySourceCode = expectedValue;
    expect(instance.supplySourceCode).to.equal(expectedValue);
  });

  it('should have the property alias', () => {
    // verify property exists
    expect(instance).to.have.property('alias');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.alias = expectedValue;
    expect(instance.alias).to.equal(expectedValue);
  });

  it('should have the property status', () => {
    // verify property exists
    expect(instance).to.have.property('status');

    // set and verify value
    const expectedValue = generateMockData('SupplySourceStatusReadOnly');
    instance.status = expectedValue;
    expect(instance.status).to.equal(expectedValue);
  });

  it('should have the property address', () => {
    // verify property exists
    expect(instance).to.have.property('address');

    // set and verify value
    const expectedValue = generateMockData('Address');
    instance.address = expectedValue;
    expect(instance.address).to.equal(expectedValue);
  });

  it('should have the property configuration', () => {
    // verify property exists
    expect(instance).to.have.property('configuration');

    // set and verify value
    const expectedValue = generateMockData('SupplySourceConfiguration');
    instance.configuration = expectedValue;
    expect(instance.configuration).to.equal(expectedValue);
  });

  it('should have the property capabilities', () => {
    // verify property exists
    expect(instance).to.have.property('capabilities');

    // set and verify value
    const expectedValue = generateMockData('SupplySourceCapabilities');
    instance.capabilities = expectedValue;
    expect(instance.capabilities).to.equal(expectedValue);
  });

  it('should have the property createdAt', () => {
    // verify property exists
    expect(instance).to.have.property('createdAt');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.createdAt = expectedValue;
    expect(instance.createdAt).to.equal(expectedValue);
  });

  it('should have the property updatedAt', () => {
    // verify property exists
    expect(instance).to.have.property('updatedAt');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.updatedAt = expectedValue;
    expect(instance.updatedAt).to.equal(expectedValue);
  });

});

// Helper function to generate random test data
function generateMockData(dataType, isArray = false) {
  if (!dataType) return {};

  // Handle array types
  if (isArray) {
    return [generateMockData(dataType), generateMockData(dataType)];
  }

  switch(dataType) {
    case 'String':
      return 'mock-' + Math.random().toString(36).substring(2, 10);
    case 'Number':
      return Math.floor(Math.random() * 1000);
    case 'Boolean':
      return Math.random() > 0.5;
    case 'Date':
      return new Date().toISOString();
    default:
      try {
        const ModelClass = SellingPartnerApiForSupplySources[dataType];
        if (ModelClass) {
          const instance = Object.create(ModelClass.prototype);
          return instance;
        }
      } catch (e) {
        console.error("Error creating instance of", dataType);
        return {};
      }
      return {};
  }
}
