/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { CapacityType } from './CapacityType.js'
import { RangeSlot } from './RangeSlot.js'

/**
 * The RangeCapacity model module.
 * @module services_v1/model/RangeCapacity
 * @version v1
 */
export class RangeCapacity {
  /**
   * Constructs a new <code>RangeCapacity</code>.
   * Range capacity entity where each entry has a capacity type and corresponding slots.
   * @alias module:services_v1/model/RangeCapacity
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>RangeCapacity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:services_v1/model/RangeCapacity} obj Optional instance to populate.
   * @return {module:services_v1/model/RangeCapacity} The populated <code>RangeCapacity</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new RangeCapacity()
      if (data.hasOwnProperty('capacityType')) { obj.capacityType = CapacityType.constructFromObject(data.capacityType) }
      if (data.hasOwnProperty('slots')) { obj.slots = ApiClient.convertToType(data.slots, [RangeSlot]) }
    }
    return obj
  }
}

/**
 * @member {module:services_v1/model/CapacityType} capacityType
 */
RangeCapacity.prototype.capacityType = undefined

/**
 * Array of capacity slots in range slot format.
 * @member {Array.<module:services_v1/model/RangeSlot>} slots
 */
RangeCapacity.prototype.slots = undefined
