/**
 * Selling Partner API for Data Kiosk
 * The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2023-11-15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
 * The GetDocumentResponse model module.
 * @module datakiosk_v2023_11_15/model/GetDocumentResponse
 * @version 2023-11-15
 */
export class GetDocumentResponse {
  /**
   * Constructs a new <code>GetDocumentResponse</code>.
   * The response for the &#x60;getDocument&#x60; operation.
   * @alias module:datakiosk_v2023_11_15/model/GetDocumentResponse
   * @class
   * @param documentId {String} The identifier for the Data Kiosk document. This identifier is unique only in combination with a selling partner account ID.
   * @param documentUrl {String} A presigned URL that can be used to retrieve the Data Kiosk document. This URL expires after 5 minutes. If the Data Kiosk document is compressed, the `Content-Encoding` header will indicate the compression algorithm.  **Note:** Most HTTP clients are capable of automatically decompressing downloaded files based on the `Content-Encoding` header.
   */
  constructor (documentId, documentUrl) {
    this.documentId = documentId
    this.documentUrl = documentUrl
  }

  /**
   * Constructs a <code>GetDocumentResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:datakiosk_v2023_11_15/model/GetDocumentResponse} obj Optional instance to populate.
   * @return {module:datakiosk_v2023_11_15/model/GetDocumentResponse} The populated <code>GetDocumentResponse</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new GetDocumentResponse()
      if (data.hasOwnProperty('documentId')) { obj.documentId = ApiClient.convertToType(data.documentId, 'String') }
      if (data.hasOwnProperty('documentUrl')) { obj.documentUrl = ApiClient.convertToType(data.documentUrl, 'String') }
    }
    return obj
  }
}

/**
 * The identifier for the Data Kiosk document. This identifier is unique only in combination with a selling partner account ID.
 * @member {String} documentId
 */
GetDocumentResponse.prototype.documentId = undefined

/**
 * A presigned URL that can be used to retrieve the Data Kiosk document. This URL expires after 5 minutes. If the Data Kiosk document is compressed, the `Content-Encoding` header will indicate the compression algorithm.  **Note:** Most HTTP clients are capable of automatically decompressing downloaded files based on the `Content-Encoding` header.
 * @member {String} documentUrl
 */
GetDocumentResponse.prototype.documentUrl = undefined
