/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js';
import { join } from 'path';

const modulePath = join(process.cwd(), 'src', 'fulfillmentoutbound_v2020_07_01', 'index.js');
const SellingPartnerApisForFulfillmentOutbound = await import(modulePath);

let instance;

beforeEach(() => {
  try {
    instance = new SellingPartnerApisForFulfillmentOutbound.GetFulfillmentPreviewRequest();
  } catch (e) {
    //Handle the cases when this model extends another model by using Model.call(this);
    instance = Object.create(SellingPartnerApisForFulfillmentOutbound.GetFulfillmentPreviewRequest.prototype);
  }
});

afterEach(() => {
  instance = null;
});

describe('GetFulfillmentPreviewRequest', () => {
  it('should create an instance of GetFulfillmentPreviewRequest', () => {
    expect(instance).to.be.a(SellingPartnerApisForFulfillmentOutbound.GetFulfillmentPreviewRequest);
  });

  it('should have the property marketplaceId', () => {
    // verify property exists
    expect(instance).to.have.property('marketplaceId');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.marketplaceId = expectedValue;
    expect(instance.marketplaceId).to.equal(expectedValue);
  });

  it('should have the property address', () => {
    // verify property exists
    expect(instance).to.have.property('address');

    // set and verify value
    const expectedValue = generateMockData('Address');
    instance.address = expectedValue;
    expect(instance.address).to.equal(expectedValue);
  });

  it('should have the property items', () => {
    // verify property exists
    expect(instance).to.have.property('items');

    // set and verify value
    const expectedValue = generateMockData('GetFulfillmentPreviewItem', true);
    instance.items = expectedValue;
    expect(instance.items).to.equal(expectedValue);
  });

  it('should have the property shippingSpeedCategories', () => {
    // verify property exists
    expect(instance).to.have.property('shippingSpeedCategories');

    // set and verify value
    const expectedValue = generateMockData('ShippingSpeedCategory', true);
    instance.shippingSpeedCategories = expectedValue;
    expect(instance.shippingSpeedCategories).to.equal(expectedValue);
  });

  it('should have the property includeCODFulfillmentPreview', () => {
    // verify property exists
    expect(instance).to.have.property('includeCODFulfillmentPreview');

    // set and verify value
    const expectedValue = generateMockData('Boolean');
    instance.includeCODFulfillmentPreview = expectedValue;
    expect(instance.includeCODFulfillmentPreview).to.equal(expectedValue);
  });

  it('should have the property includeDeliveryWindows', () => {
    // verify property exists
    expect(instance).to.have.property('includeDeliveryWindows');

    // set and verify value
    const expectedValue = generateMockData('Boolean');
    instance.includeDeliveryWindows = expectedValue;
    expect(instance.includeDeliveryWindows).to.equal(expectedValue);
  });

  it('should have the property featureConstraints', () => {
    // verify property exists
    expect(instance).to.have.property('featureConstraints');

    // set and verify value
    const expectedValue = generateMockData('FeatureSettings', true);
    instance.featureConstraints = expectedValue;
    expect(instance.featureConstraints).to.equal(expectedValue);
  });

});

// Helper function to generate random test data
function generateMockData(dataType, isArray = false) {
  if (!dataType) return {};

  // Handle array types
  if (isArray) {
    return [generateMockData(dataType), generateMockData(dataType)];
  }

  switch(dataType) {
    case 'String':
      return 'mock-' + Math.random().toString(36).substring(2, 10);
    case 'Number':
      return Math.floor(Math.random() * 1000);
    case 'Boolean':
      return Math.random() > 0.5;
    case 'Date':
      return new Date().toISOString();
    default:
      try {
        const ModelClass = SellingPartnerApisForFulfillmentOutbound[dataType];
        if (ModelClass) {
          const instance = Object.create(ModelClass.prototype);
          return instance;
        }
      } catch (e) {
        console.error("Error creating instance of", dataType);
        return {};
      }
      return {};
  }
}
