/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js';
import { join } from 'path';

const modulePath = join(process.cwd(), 'src', 'fulfillmentoutbound_v2020_07_01', 'index.js');
const SellingPartnerApisForFulfillmentOutbound = await import(modulePath);

let instance;

beforeEach(() => {
  try {
    instance = new SellingPartnerApisForFulfillmentOutbound.UpdateFulfillmentOrderItem();
  } catch (e) {
    //Handle the cases when this model extends another model by using Model.call(this);
    instance = Object.create(SellingPartnerApisForFulfillmentOutbound.UpdateFulfillmentOrderItem.prototype);
  }
});

afterEach(() => {
  instance = null;
});

describe('UpdateFulfillmentOrderItem', () => {
  it('should create an instance of UpdateFulfillmentOrderItem', () => {
    expect(instance).to.be.a(SellingPartnerApisForFulfillmentOutbound.UpdateFulfillmentOrderItem);
  });

  it('should have the property sellerSku', () => {
    // verify property exists
    expect(instance).to.have.property('sellerSku');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.sellerSku = expectedValue;
    expect(instance.sellerSku).to.equal(expectedValue);
  });

  it('should have the property sellerFulfillmentOrderItemId', () => {
    // verify property exists
    expect(instance).to.have.property('sellerFulfillmentOrderItemId');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.sellerFulfillmentOrderItemId = expectedValue;
    expect(instance.sellerFulfillmentOrderItemId).to.equal(expectedValue);
  });

  it('should have the property quantity', () => {
    // verify property exists
    expect(instance).to.have.property('quantity');

    // set and verify value
    const expectedValue = generateMockData('Number');
    instance.quantity = expectedValue;
    expect(instance.quantity).to.equal(expectedValue);
  });

  it('should have the property giftMessage', () => {
    // verify property exists
    expect(instance).to.have.property('giftMessage');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.giftMessage = expectedValue;
    expect(instance.giftMessage).to.equal(expectedValue);
  });

  it('should have the property displayableComment', () => {
    // verify property exists
    expect(instance).to.have.property('displayableComment');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.displayableComment = expectedValue;
    expect(instance.displayableComment).to.equal(expectedValue);
  });

  it('should have the property fulfillmentNetworkSku', () => {
    // verify property exists
    expect(instance).to.have.property('fulfillmentNetworkSku');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.fulfillmentNetworkSku = expectedValue;
    expect(instance.fulfillmentNetworkSku).to.equal(expectedValue);
  });

  it('should have the property orderItemDisposition', () => {
    // verify property exists
    expect(instance).to.have.property('orderItemDisposition');

    // set and verify value
    const expectedValue = generateMockData('String');
    instance.orderItemDisposition = expectedValue;
    expect(instance.orderItemDisposition).to.equal(expectedValue);
  });

  it('should have the property perUnitDeclaredValue', () => {
    // verify property exists
    expect(instance).to.have.property('perUnitDeclaredValue');

    // set and verify value
    const expectedValue = generateMockData('Money');
    instance.perUnitDeclaredValue = expectedValue;
    expect(instance.perUnitDeclaredValue).to.equal(expectedValue);
  });

  it('should have the property perUnitPrice', () => {
    // verify property exists
    expect(instance).to.have.property('perUnitPrice');

    // set and verify value
    const expectedValue = generateMockData('Money');
    instance.perUnitPrice = expectedValue;
    expect(instance.perUnitPrice).to.equal(expectedValue);
  });

  it('should have the property perUnitTax', () => {
    // verify property exists
    expect(instance).to.have.property('perUnitTax');

    // set and verify value
    const expectedValue = generateMockData('Money');
    instance.perUnitTax = expectedValue;
    expect(instance.perUnitTax).to.equal(expectedValue);
  });

});

// Helper function to generate random test data
function generateMockData(dataType, isArray = false) {
  if (!dataType) return {};

  // Handle array types
  if (isArray) {
    return [generateMockData(dataType), generateMockData(dataType)];
  }

  switch(dataType) {
    case 'String':
      return 'mock-' + Math.random().toString(36).substring(2, 10);
    case 'Number':
      return Math.floor(Math.random() * 1000);
    case 'Boolean':
      return Math.random() > 0.5;
    case 'Date':
      return new Date().toISOString();
    default:
      try {
        const ModelClass = SellingPartnerApisForFulfillmentOutbound[dataType];
        if (ModelClass) {
          const instance = Object.create(ModelClass.prototype);
          return instance;
        }
      } catch (e) {
        console.error("Error creating instance of", dataType);
        return {};
      }
      return {};
  }
}
