/**
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
 * The Dimensions model module.
 * @module vendorshipments_v1/model/Dimensions
 * @version v1
 */
export class Dimensions {
  /**
   * Constructs a new <code>Dimensions</code>.
   * Physical dimensional measurements of a container.
   * @alias module:vendorshipments_v1/model/Dimensions
   * @class
   * @param length {String} A decimal number with no loss of precision. Useful when precision loss is unacceptable, as with currencies. Follows RFC7159 for number representation. <br>**Pattern** : `^-?(0|([1-9]\\d*))(\\.\\d+)?([eE][+-]?\\d+)?$`.
   * @param width {String} A decimal number with no loss of precision. Useful when precision loss is unacceptable, as with currencies. Follows RFC7159 for number representation. <br>**Pattern** : `^-?(0|([1-9]\\d*))(\\.\\d+)?([eE][+-]?\\d+)?$`.
   * @param height {String} A decimal number with no loss of precision. Useful when precision loss is unacceptable, as with currencies. Follows RFC7159 for number representation. <br>**Pattern** : `^-?(0|([1-9]\\d*))(\\.\\d+)?([eE][+-]?\\d+)?$`.
   * @param unitOfMeasure {module:vendorshipments_v1/model/Dimensions.UnitOfMeasureEnum} The unit of measure for dimensions.
   */
  constructor (length, width, height, unitOfMeasure) {
    this.length = length
    this.width = width
    this.height = height
    this.unitOfMeasure = unitOfMeasure
  }

  /**
   * Constructs a <code>Dimensions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendorshipments_v1/model/Dimensions} obj Optional instance to populate.
   * @return {module:vendorshipments_v1/model/Dimensions} The populated <code>Dimensions</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new Dimensions()
      if (data.hasOwnProperty('length')) { obj.length = ApiClient.convertToType(data.length, 'String') }
      if (data.hasOwnProperty('width')) { obj.width = ApiClient.convertToType(data.width, 'String') }
      if (data.hasOwnProperty('height')) { obj.height = ApiClient.convertToType(data.height, 'String') }
      if (data.hasOwnProperty('unitOfMeasure')) { obj.unitOfMeasure = ApiClient.convertToType(data.unitOfMeasure, 'String') }
    }
    return obj
  }
}

/**
 * A decimal number with no loss of precision. Useful when precision loss is unacceptable, as with currencies. Follows RFC7159 for number representation. <br>**Pattern** : `^-?(0|([1-9]\\d*))(\\.\\d+)?([eE][+-]?\\d+)?$`.
 * @member {String} length
 */
Dimensions.prototype.length = undefined

/**
 * A decimal number with no loss of precision. Useful when precision loss is unacceptable, as with currencies. Follows RFC7159 for number representation. <br>**Pattern** : `^-?(0|([1-9]\\d*))(\\.\\d+)?([eE][+-]?\\d+)?$`.
 * @member {String} width
 */
Dimensions.prototype.width = undefined

/**
 * A decimal number with no loss of precision. Useful when precision loss is unacceptable, as with currencies. Follows RFC7159 for number representation. <br>**Pattern** : `^-?(0|([1-9]\\d*))(\\.\\d+)?([eE][+-]?\\d+)?$`.
 * @member {String} height
 */
Dimensions.prototype.height = undefined

/**
 * Allowed values for the <code>unitOfMeasure</code> property.
 * @enum {String}
 * @readonly
 */
Dimensions.UnitOfMeasureEnum = {

  /**
     * value: "In"
     * @const
     */
  In: 'In',

  /**
     * value: "Ft"
     * @const
     */
  Ft: 'Ft',

  /**
     * value: "Meter"
     * @const
     */
  Meter: 'Meter',

  /**
     * value: "Yard"
     * @const
     */
  Yard: 'Yard'
}

/**
 * The unit of measure for dimensions.
 * @member {module:vendorshipments_v1/model/Dimensions.UnitOfMeasureEnum} unitOfMeasure
 */
Dimensions.prototype.unitOfMeasure = undefined
