/**
 * The Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The ProductContext model module.
 * @module finances_2024_06_19/model/ProductContext
 * @version 2024-06-19
 */
export class ProductContext {
  /**
   * Constructs a new <code>ProductContext</code>.
   * Additional information related to the product.
   * @alias module:finances_2024_06_19/model/ProductContext
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:finances_2024_06_19/model/ProductContext} obj Optional instance to populate.
   * @return {module:finances_2024_06_19/model/ProductContext} The populated <code>ProductContext</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new ProductContext();
      if (data.hasOwnProperty('asin'))
        obj.asin = ApiClient.convertToType(data['asin'], 'String');
      if (data.hasOwnProperty('sku'))
        obj.sku = ApiClient.convertToType(data['sku'], 'String');
      if (data.hasOwnProperty('quantityShipped'))
        obj.quantityShipped = ApiClient.convertToType(data['quantityShipped'], 'Number');
      if (data.hasOwnProperty('fulfillmentNetwork'))
        obj.fulfillmentNetwork = ApiClient.convertToType(data['fulfillmentNetwork'], 'String');
    }
    return obj;
  }
}

/**
 * Amazon Standard Identification Number (ASIN) of the item.
 * @member {String} asin
 */
ProductContext.prototype.asin = undefined;

/**
 * Stock keeping unit (SKU) of the item.
 * @member {String} sku
 */
ProductContext.prototype.sku = undefined;

/**
 * Quantity of the item shipped.
 * @member {Number} quantityShipped
 */
ProductContext.prototype.quantityShipped = undefined;

/**
 * Fulfillment network of the item.
 * @member {String} fulfillmentNetwork
 */
ProductContext.prototype.fulfillmentNetwork = undefined;


