/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { TransferSchedule } from './TransferSchedule.js'

/**
 * The TransferScheduleListing model module.
 * @module sellerWallet_2024_03_01/model/TransferScheduleListing
 * @version 2024-03-01
 */
export class TransferScheduleListing {
  /**
   * Constructs a new <code>TransferScheduleListing</code>.
   * A list of transfer schedules.
   * @alias module:sellerWallet_2024_03_01/model/TransferScheduleListing
   * @class
   * @param transferSchedules {Array.<module:sellerWallet_2024_03_01/model/TransferSchedule>} A list of transfer schedules.
   */
  constructor (transferSchedules) {
    this.transferSchedules = transferSchedules
  }

  /**
   * Constructs a <code>TransferScheduleListing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellerWallet_2024_03_01/model/TransferScheduleListing} obj Optional instance to populate.
   * @return {module:sellerWallet_2024_03_01/model/TransferScheduleListing} The populated <code>TransferScheduleListing</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new TransferScheduleListing()
      if (data.hasOwnProperty('nextPageToken')) { obj.nextPageToken = ApiClient.convertToType(data.nextPageToken, 'String') }
      if (data.hasOwnProperty('transferSchedules')) { obj.transferSchedules = ApiClient.convertToType(data.transferSchedules, [TransferSchedule]) }
    }
    return obj
  }
}

/**
 * A token that you use to retrieve the next page of results. The response includes `nextPageToken` when the number of results exceeds 100. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextPageToken` is null. Note that this operation can return empty pages.
 * @member {String} nextPageToken
 */
TransferScheduleListing.prototype.nextPageToken = undefined

/**
 * A list of transfer schedules.
 * @member {Array.<module:sellerWallet_2024_03_01/model/TransferSchedule>} transferSchedules
 */
TransferScheduleListing.prototype.transferSchedules = undefined
